number1 = int(input("1. sayı girin:"))
number2 = int(input("2. sayı girin:"))
print(f"{number1} + {number2} = {number1 + number2}")
print(f"{number1} - {number2} = {number1 - number2}")
print(f"{number1} * {number2} = {number1 * number2}")
print(f"{number1} / {number2} = {number1 // number2}")